---
- name: 'configure_systemd | Определить путь к env-файлу в зависимости от ОС'
  ansible.builtin.set_fact:
    zbxtelegram_env_file: >-
      {{ os_env_paths[ansible_os_family] | default('/etc/default') }}/zbxtelegrambot
  vars:
    os_env_paths:
      Red: /etc/sysconfig
      RED: /etc/sysconfig
      RedHat: /etc/sysconfig   # RHEL, CentOS, AlmaLinux, Rocky, Oracle, RED OS
      Debian: /etc/default     # Ubuntu, Debian, Linux Mint, Pop!_OS

- name: 'configure_systemd | Сгенерировать файл переменных окружения'
  tags:
    - systemd
  template:
    src: "zbxtelegrambot.env.j2"
    dest: "{{ zbxtelegram_env_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart zbxtelegrambot

- name: 'configure_systemd | Сгенерировать systemd unit'
  tags:
    - systemd
  template:
    src: "zbxtelegrambot.service.j2"
    dest: "/etc/systemd/system/{{ zbxtelegram_service_name }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Reload systemd
    - Restart zbxtelegrambot

- name: 'configure_systemd | Включить и запустить сервис'
  tags:
    - systemd
  systemd:
    name: "{{ zbxtelegram_service_name }}"
    enabled: true
    state: started
    daemon_reload: true

...
